<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Dữ liệu mẫu cho sản phẩm
        $products = [
            [
                'name' => 'Áo Thun Polo Nam Tay Bo Trơn Form Fitted - 10S24POL012',
                'price_import' => 540000,
                'price_sell' => 500000,
                'img' => '1719206230.jpg',
                'description' => 'Áo thun polo nam tay bo trơn form fitted được làm từ chất liệu cotton pha polyester mềm mại, thoáng mát. Áo có thiết kế cổ bẻ, tay ngắn, bo thun, form ôm vừa vặn, tôn dáng người mặc. Áo phù hợp cho nhiều hoạt động khác nhau như đi chơi, đi học, đi làm...',
                'status' => 1,
                'category_id' => 4,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Polo Nam Tay Ngắn Dệt Jacquard Phối Nhãn Form Loose - 10S24POL010',
                'price_import' => 471000,
                'price_sell' => 450000,
                'img' => 'ao-polo-2-1.jpg',
                'description' => 'Áo thun polo nam cổ polo họa tiết jacquard form loose được làm từ chất liệu jacquard cao cấp, mềm mại, thoáng mát. Áo có thiết kế cổ bẻ thanh lịch, tay ngắn, form rộng rãi, thoải mái. Họa tiết jacquard tinh tế trên thân áo tạo điểm nhấn sang trọng và đẳng cấp. Áo phù hợp cho nhiều hoạt động khác nhau như đi chơi, đi học, đi làm...',
                'status' => 1,
                'category_id' => 4,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Polo Nam Tay Ngắn Cotton Pique Phối Rib Form Regular - 10F23POL009',
                'price_import' => 540000,
                'price_sell' => 500000,
                'img' => 'ao-polo-nam-12-10f23pol009.jpg.jpg',
                'description' => 'Áo thun polo nam tay ngắn phối màu form regular được làm từ chất liệu cotton pique mềm mại, thoáng mát, thấm hút mồ hôi tốt, mang lại cảm giác thoải mái khi mặc trong mọi điều kiện thời tiết. Áo có thiết kế cổ bẻ thanh lịch, tay ngắn, form regular vừa vặn, tôn dáng người mặc. Phối màu tinh tế, hiện đại tạo điểm nhấn cho chiếc áo. Áo phù hợp cho nhiều hoạt động khác nhau như đi chơi, đi học, đi làm...',
                'status' => 1,
                'category_id' => 4,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Polo Nam Tay Ngắn Phối Màu Form Fitted - 10F23POL028',
                'price_import' => 392000,
                'price_sell' => 370000,
                'img' => 'ao-polo-nam-4-1.jpg',
                'description' => 'Áo thun polo nam tay ngắn phối màu form fitted được làm từ chất liệu CVC mềm mại, thoáng mát, thấm hút mồ hôi tốt, mang lại cảm giác thoải mái khi mặc. Áo có thiết kế cổ bẻ thanh lịch, tay ngắn, form ôm vừa vặn, tôn dáng người mặc. Phối màu tinh tế, hiện đại tạo điểm nhấn cho chiếc áo. Áo phù hợp cho nhiều hoạt động khác nhau như đi chơi, đi học, đi làm...',
                'status' => 1,
                'category_id' => 4,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Polo Nam Rút Dây Phối Túi Dây Kéo Form Regular - 10F23POL034',
                'price_import' => 414000,
                'price_sell' => 308000,
                'img' => 'ao-polo-nam-5-1.jpg',
                'description' => 'Áo thun polo nam cổ gài nút tay bo form regular được làm từ chất liệu cotton mềm mại, thoáng mát, thấm hút mồ hôi tốt, mang lại cảm giác thoải mái khi mặc trong mọi điều kiện thời tiết. Áo có thiết kế cổ gài nút thanh lịch, tay ngắn bo thun, form regular vừa vặn, tôn dáng người mặc. Phối màu tinh tế, hiện đại tạo điểm nhấn cho chiếc áo. Áo phù hợp cho nhiều hoạt động khác nhau như đi chơi, đi học, đi làm...',
                'status' => 1,
                'category_id' => 4,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Polo Nam Tay Bo 100% Cotton Phối Màu Form Fitted - 10S23POL032',
                'price_import' => 490000,
                'price_sell' => 490000,
                'img' => 'ao-polo-nam-6-1.jpg',
                'description' => 'Áo thun polo nam cổ gài nút tay bo form fitted được làm từ 100% chất liệu cotton mềm mại, thoáng mát, thấm hút mồ hôi tốt, mang lại cảm giác thoải mái khi mặc trong mọi điều kiện thời tiết. Áo có thiết kế cổ gài nút thanh lịch, tay ngắn bo thun, form ôm vừa vặn, tôn dáng người mặc. Phối màu tinh tế, hiện đại tạo điểm nhấn cho chiếc áo. Áo phù hợp cho nhiều hoạt động khác nhau như đi chơi, đi học, đi làm...',
                'status' => 1,
                'category_id' => 4,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Thun Tay Ngắn Sinh Nhật Routine 11 Tuổi Form Loose - 10S24TSS082',
                'price_import' => 490000,
                'price_sell' => 490000,
                'img' => 'ao-thun-1-1.jpg',
                'description' => 'Áo thun polo nam cổ gài nút tay bo form fitted được làm từ 100% chất liệu cotton mềm mại, thoáng mát, thấm hút mồ hôi tốt, mang lại cảm giác thoải mái khi mặc trong mọi điều kiện thời tiết. Áo có thiết kế cổ gài nút thanh lịch, tay ngắn bo thun, form ôm vừa vặn, tôn dáng người mặc. Phối màu tinh tế, hiện đại tạo điểm nhấn cho chiếc áo. Áo phù hợp cho nhiều hoạt động khác nhau như đi chơi, đi học, đi làm...',
                'status' => 1,
                'category_id' => 5,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Thun Tay Ngắn Unisex Cotton In Hình Form Loose - 10S24TSSU006',
                'price_import' => 392000,
                'price_sell' => 392000,
                'img' => 'ao-thun-2-1.jpg',
                'description' => 'Áo thun unisex form loose cổ tròn tay ngắn trơn được làm từ chất liệu Coffee Poly mềm mại, thoáng mát, thấm hút mồ hôi tốt, mang lại cảm giác thoải mái khi mặc trong mọi điều kiện thời tiết. Áo có thiết kế form loose rộng rãi, thoải mái, phù hợp cho cả nam và nữ. Cổ áo tròn basic, tay ngắn tiện lợi. Kiểu dáng trơn đơn giản, dễ dàng phối đồ với nhiều phong cách khác nhau. Áo phù hợp cho nhiều hoạt động khác nhau như đi chơi, đi học, đi làm, tập thể dục thể thao...',
                'status' => 1,
                'category_id' => 5,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Thun Nam Tay Ngắn Premium Jacquard Trơn Form Fitted - 10S24TSS037P',
                'price_import' => 441000,
                'price_sell' => 441000,
                'img' => 'ao-thun-3-1.jpg',
                'description' => 'Áo thun unisex form loose cổ tròn tay ngắn trơn được làm từ chất liệu Coffee Poly mềm mại, thoáng mát, thấm hút mồ hôi tốt, mang lại cảm giác thoải mái khi mặc trong mọi điều kiện thời tiết. Áo có thiết kế form loose rộng rãi, thoải mái, phù hợp cho cả nam và nữ. Cổ áo tròn basic, tay ngắn tiện lợi. Kiểu dáng trơn đơn giản, dễ dàng phối đồ với nhiều phong cách khác nhau. Áo phù hợp cho nhiều hoạt động khác nhau như đi chơi, đi học, đi làm, tập thể dục thể thao...',
                'status' => 1,
                'category_id' => 5,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Thun Nam Tay Ngắn 100% Cotton In Hình Form Loose - 10S24TSS005',
                'price_import' => 343000,
                'price_sell' => 343000,
                'img' => 'ao-thun-4-1.jpg',
                'description' => 'Áo thun nam form loose cổ tròn tay ngắn họa tiết được làm từ 100% chất liệu cotton cao cấp, mềm mại, thoáng mát, thấm hút mồ hôi tốt, mang lại cảm giác thoải mái khi mặc trong mọi điều kiện thời tiết. Áo có thiết kế form loose rộng rãi, thoải mái, phù hợp cho nam giới. Họa tiết bắt mắt, trẻ trung, tạo điểm nhấn cho chiếc áo. Cổ tròn basic, tay ngắn tiện lợi. Kiểu dáng đơn giản, dễ dàng phối đồ với nhiều phong cách khác nhau. Áo phù hợp cho nhiều hoạt động khác nhau như đi chơi, đi học, đi làm, dạo phố...',
                'status' => 1,
                'category_id' => 5,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Thun Nam Tay Ngắn Dệt Jacquard Phối Nhãn Form Loose - 10S24TSS014',
                'price_import' => 392000,
                'price_sell' => 392000,
                'img' => 'ao-thun-5-1.jpg',
                'description' => 'Áo thun nam form loose cổ tròn tay ngắn họa tiết jacquard được làm từ chất liệu jacquard cao cấp, mềm mại, thoáng mát, thấm hút mồ hôi tốt, mang lại cảm giác thoải mái khi mặc trong mọi điều kiện thời tiết. Áo có thiết kế form loose rộng rãi, thoải mái, phù hợp cho nam giới. Họa tiết jacquard tinh tế, sang trọng, tạo điểm nhấn cho chiếc áo. Cổ tròn basic, tay ngắn tiện lợi. Kiểu dáng đơn giản, dễ dàng phối đồ với nhiều phong cách khác nhau. Áo phù hợp cho nhiều hoạt động khác nhau như đi chơi, đi học, đi làm, dạo phố...',
                'status' => 1,
                'category_id' => 5,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Thun Nam Tay Ngắn Cổ Tròn Phối Rib Trơn Form Loose - 10S24TSS011',
                'price_import' => 392000,
                'price_sell' => 392000,
                'img' => 'ao-thun-6-1.jpg',
                'description' => 'Áo thun nam form loose cổ tròn tay ngắn trơn được làm từ 100% chất liệu cotton cao cấp, mềm mại, thoáng mát, thấm hút mồ hôi tốt, mang lại cảm giác thoải mái khi mặc trong mọi điều kiện thời tiết. Áo có thiết kế form loose rộng rãi, thoải mái, phù hợp cho nam giới mọi vóc dáng. Cổ tròn basic, tay ngắn tiện lợi. Kiểu dáng trơn đơn giản, dễ dàng phối đồ với nhiều phong cách khác nhau. Áo phù hợp cho nhiều hoạt động khác nhau như đi chơi, đi học, đi làm, dạo phố...',
                'status' => 1,
                'category_id' => 5,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sơ Mi Nam Tay Dài Trơn Form Fitted - 10F24SHL005',
                'price_import' => 471000,
                'price_sell' => 471000,
                'img' => 'ao-so-mi-1-1.jpg',
                'description' => 'Áo sơ mi nam tay ngắn được làm từ chất liệu cotton 100% mềm mại, thoáng mát, thấm hút mồ hôi tốt. Áo có thiết kế form regular vừa vặn, túi đắp trước ngực, cổ bẻ ve nhọn. Áo phù hợp cho nhiều hoạt động khác nhau như đi chơi, đi học, đi làm.',
                'status' => 1,
                'category_id' => 6,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sơ Mi Nam Tay Ngắn Cotton Túi Đắp Trơn Form Regular - 10S24SHS002',
                'price_import' => 490000,
                'price_sell' => 490000,
                'img' => 'ao-so-mi-2-1.jpg',
                'description' => 'Form dáng: Regular
                                Giới tính: Nam
                                Chất liệu: 100% Cotton
                                Thiết kế: Trơn
                                Kiểu tay: Tay ngắn
                                Kiểu cổ: Cổ sơ mi
                                Kiểu túi: Túi đắp',
                'category_id' => 6,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sơ Mi Nam Tay Ngắn Họa Tiết Kẻ Sọc Form Oversize - 10S24SHS003',
                'price_import' => 471000,
                'price_sell' => 471000,
                'img' => 'ao-so-mi-3-1.jpg',
                'description' => '
                        - Form dáng: Oversize
                        - Giới tính: Nam
                        - Chất liệu: Cotton Polyester
                        - Thiết kế: Họa tiết
                        - Kiểu tay: Tay ngắn
                        - Kiểu cổ:Cổ sơ mi',
                'category_id' => 6,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sơ Mi Nam Tay Dài Kẻ Sọc 100% Cotton Form Loose - 10S24SHL003',
                'price_import' => 540000,
                'price_sell' => 540000,
                'img' => 'ao-so-mi-4-1.jpg',
                'description' => '
                        - Form dáng: Loose
                        - Giới tính: Nam
                        - Chất liệu: 100% Cotton
                        - Thiết kế: Họa tiết
                        - Kiểu tay: Tay dài
                        - Kiểu cổ: Cổ sơ mi',
                'category_id' => 6,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sơ Mi Denim Nam Tay Ngắn Thêu Chữ Form Regular - 10S24DSH001',
                'price_import' => 540000,
                'price_sell' => 540000,
                'img' => 'ao-so-mi-5-1.jpg',
                'description' => '
                        - Form dáng: Regular
                        - Giới tính: Nam
                        - Chất liệu: Denim
                        - Thiết kế: Họa tiết
                        - Kiểu tay: Tay ngắn
                        - Kiểu cổ: Cổ sơ mi',
                'category_id' => 6,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sơ Mi Jean Unisex 100% Cotton Trơn Form Loose - 10S24DSHU001',
                'price_import' => 540000,
                'price_sell' => 540000,
                'img' => 'ao-so-mi-6-1.jpg',
                'description' => '
                        - Form dáng: Loose
                        - Giới tính: Unisex
                        - Chất liệu: 100% Cotton
                        - Thiết kế: Trơn
                        - Kiểu tay: Tay lửng
                        - Kiểu cổ: Cổ lớn',
                'category_id' => 6,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Khoác Bomber Nam Da Lộn Trơn Dây Kéo Form Regular - 10F23JAC001',
                'price_import' => 1178000,
                'price_sell' => 1178000,
                'img' => 'ao-khoac-1-1.jpg',
                'description' => '
                            Form dáng: Regular (bình thường, không ôm sát)
                            Giới tính: Nam
                            Chất liệu: Polyester
                            Thiết kế: Trơn (không có hoa văn hay họa tiết)
                            Kiểu tay: Tay dài
                            Kiểu cổ: Cổ cao',
                'category_id' => 7,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Khoác Nam Flannel Tay Dài Khóa Kéo Kẻ Caro Form Regular - 10F23JAC002',
                'price_import' => 981000,
                'price_sell' => 981000,
                'img' => 'ao-khoac-2-1.jpg',
                'description' => 'Form dáng: Regular (bình thường, không ôm sát)
                            Giới tính: Nam
                            Chất liệu: Flannel
                            Thiết kế: Phối màu (có sự kết hợp giữa các màu sắc khác nhau)
                            Kiểu tay: Tay dài
                            Kiểu cổ: Cổ khóa kéo (cổ có khóa kéo để đóng mở)
                            Kiểu túi: Túi đắp (có túi có nắp đắp phía trước áo)',
                'category_id' => 7,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Khoác Bomber Nam Nylon Chần Bông Phối Màu Form Regular - 10F23JAC006',
                'price_import' => 981000,
                'price_sell' => 981000,
                'img' => 'ao-khoac-3-1.jpg',
                'description' => 'Nhóm sản phẩm: Áo Khoác
                            Form dáng: Regular (bình thường, không ôm sát)
                            Giới tính: Nam
                            Chất liệu: Nylon
                            Thiết kế: Phối màu (có sự kết hợp giữa các màu sắc khác nhau)
                            Kiểu tay: Tay dài
                            Kiểu cổ: Cổ cao
                            Kiểu túi: Túi đắp (có túi có nắp đắp phía trước áo)',
                'category_id' => 7,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Khoác Chần Bông Nam Cổ Trụ Phối Rib Form Regular - 10F23JAC007',
                'price_import' => 1374000,
                'price_sell' => 1374000,
                'img' => 'ao-khoac-4-1.jpg',
                'description' => 'Form dáng: Regular (bình thường, không ôm sát)
                            Giới tính: Nam
                            Chất liệu: Polyester
                            Thiết kế: Phối màu (có sự kết hợp giữa các màu sắc khác nhau)
                            Kiểu tay: Tay dài
                            Kiểu cổ: Cổ trụ (cổ cao và thẳng đứng)
                            Kiểu túi: Túi có nắp (có túi có nắp đậy phía trước áo)',
                'category_id' => 7,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Khoác Nam Dây Kéo Cổ Trụ Phối Rib Form Regular - 10F23JAC008',
                'price_import' => 1129000,
                'price_sell' => 1129000,
                'img' => 'ao-khoac-5-1.jpg',
                'description' => 'Form dáng: Regular (bình thường, không ôm sát)
                            Giới tính: Nam
                            Chất liệu: Polyester
                            Thiết kế: Phối màu (có sự kết hợp giữa các màu sắc khác nhau)
                            Kiểu tay: Tay dài
                            Kiểu cổ: Cổ trụ (cổ cao và thẳng đứng)
                            Kiểu túi: Túi đắp (có túi có nắp đắp phía trước áo)',
                'category_id' => 7,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Khoác Bomber Nam Kaki Khóa Kéo Gập Ly Form Regular - 10F23JAC009',
                'price_import' => 1178000,
                'price_sell' => 1178000,
                'img' => 'ao-khoac-6-1.jpg',
                'description' => 'Form dáng: Regular (bình thường, không ôm sát)
                            Giới tính: Nam
                            Chất liệu: Kaki
                            Thiết kế: Trơn (không có hoa văn hay họa tiết)
                            Kiểu tay: Tay dài
                            Kiểu cổ: Cổ khóa kéo (cổ có khóa kéo để đóng mở)
                            Kiểu túi: Túi đắp (có túi có nắp đắp phía trước áo)',
                'category_id' => 7,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Hoodie Unisex Tay Dài Có Túi Mũ In Hình Form Loose - 10F23HODU003',
                'price_import' => 638000,
                'price_sell' => 638000,
                'img' => 'ao-hoodie-1-1.jpg',
                'description' => 'có form dáng rộng rãi phù hợp cho cả nam và nữ. Chất liệu chủ yếu là cotton, thiết kế với họa tiết đa dạng và kiểu túi lớn tiện dụng, cùng với kiểu tay dài.',
                'category_id' => 8,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sweater Nam Basic Cổ Tròn Nhãn Trang Trí Form Regular - 10F23SWE001',
                'price_import' => 540000,
                'price_sell' => 540000,
                'img' => 'ao-hoodie-2-1.jpg',
                'description' => 'hoodie/sweater dành cho nam, có form dáng regular (vừa vặn). Chất liệu chủ yếu là cotton, thiết kế trơn và kiểu cổ tròn, đi kèm với tay dài.',
                'category_id' => 8,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Hoodie Nam Tay Dài Có Mũ Texture Trơn Form Regular - 10S23HOD009',
                'price_import' => 589000,
                'price_sell' => 412000,
                'img' => 'ao-hoodie-3-1.jpg',
                'description' => 'áo hoodie/sweater dành cho nam, có form dáng regular (vừa vặn). Chất liệu chủ yếu là cotton, thiết kế trơn và có kiểu cổ gài nút, cùng với tay dài.',
                'category_id' => 8,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sweater Nam Thêu Hình Phối Piping Form Regular - 10F22SWE005',
                'price_import' => 529000,
                'price_sell' => 520000,
                'img' => 'ao-hoodie-4-1.jpg',
                'description' => 'áo hoodie/sweater dành cho nam, có form dáng regular (vừa vặn) và làm từ chất liệu cotton. Áo có kiểu tay dài và kiểu cổ tròn.',
                'category_id' => 8,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sweater Nam Tay Dài Vải Nỉ Thêu Logo Form Regular - 10F22SWE001',
                'price_import' => 450000,
                'price_sell' => 450000,
                'img' => 'ao-hoodie-5-1.jpg',
                'description' => 'áo hoodie/sweater dành cho nam, có form dáng regular (vừa vặn) và làm từ chất liệu nỉ. Áo thiết kế trơn, có kiểu tay dài và kiểu cổ tròn.',
                'category_id' => 8,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Hoodie Thể Thao Tay Ngắn Có Nón Form Regular - 10F21HODA001',
                'price_import' => 980000,
                'price_sell' => 890000,
                'img' => 'ao-hoodie-6-1.jpg',
                'description' => 'áo hoodie/sweater dành cho nam, có form dáng regular (vừa vặn) và làm từ chất liệu nylon. Áo có kiểu tay ngắn, phù hợp để sử dụng trong môi trường nóng',
                'category_id' => 8,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Jean Nam Ống Ôm Túi Đắp Trơn Form Slim - 10S24DPA006',
                'price_import' => 589000,
                'price_sell' => 589000,
                'img' => 'quan-jean-1-1.jpg',
                'description' => 'quần jean dành cho nam, có form dáng slim (vừa ôm vừa thon gọn), được làm từ chất liệu cotton spandex. Quần có thiết kế trơn, với kiểu túi đắp.',
                'category_id' => 9,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Jean Nam Ống Ôm Trơn Form Slim Cropped - 10S23DPA108CR2',
                'price_import' => 472000,
                'price_sell' => 472000,
                'img' => 'quan-jean-2-1.jpg',
                'description' => 'quần jean dành cho nam, có form dáng slim cropped (vừa ôm vừa ngắn) và làm từ chất liệu cotton. Quần có thiết kế trơn, mang lại sự thoải mái và phong cách hiện đại cho người mặc.',
                'category_id' => 9,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Jean Nam Ống Ôm Xanh Trơn Cotton Spandex Form Slim - 10S24DPA004',
                'price_import' => 598000,
                'price_sell' => 598000,
                'img' => 'quan-jean-3-1.jpg',
                'description' => 'quần jean dành cho nam, có form dáng slim (vừa ôm vừa thon gọn), được làm từ chất liệu cotton spandex. Quần có thiết kế trơn và đi kèm kiểu túi đắp, tạo nên sự thoải mái và phong cách lịch lãm cho người mặc.',
                'category_id' => 9,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Jean Nam Ống Ôm Xanh Trơn Form Slim - 10S24DPA005',
                'price_import' => 589000,
                'price_sell' => 589000,
                'img' => 'quan-jean-4-1.jpg',
                'description' => 'quần jean dành cho nam, có form dáng slim (vừa ôm vừa thon gọn), được làm từ chất liệu cotton spandex. Quần có thiết kế trơn và đi kèm kiểu túi đắp, tạo nên sự thoải mái và phong cách hiện đại cho người mặc.',
                'category_id' => 9,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Jean Nam Ống Ôm Spandex Co Giãn Form Slim - 10S24DPA003',
                'price_import' => 589000,
                'price_sell' => 589000,
                'img' => 'quan-jean-5-1.jpg',
                'description' => 'quần jean dành cho nam, có form dáng slim (vừa ôm vừa thon gọn), được làm từ chất liệu cotton spandex. Quần có thiết kế phối màu và đi kèm kiểu túi đắp, tạo nên sự nổi bật và thời trang cho người mặc.',
                'category_id' => 9,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Jean Nam Ống Ôm Trơn Phối Màu Form Slim - 10F23DPA012P',
                'price_import' => 687000,
                'price_sell' => 687000,
                'img' => 'quan-jean-6-1.jpg',
                'description' => 'quần jean dành cho nam, có form dáng slim (vừa ôm vừa thon gọn), được làm từ chất liệu jeans. Quần có thiết kế phối màu và đi kèm kiểu túi đắp, mang đến sự sang trọng và phong cách đặc trưng cho người mặc.',
                'category_id' => 9,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Kaki Nam Premium Ống Ôm Trơn Cotton Form Slim - 10S24PCA002P',
                'price_import' => 638000,
                'price_sell' => 638000,
                'img' => 'quan-kaki-1-1.jpg',
                'description' => 'quần kaki dành cho nam, có form dáng slim (vừa ôm vừa thon gọn) và làm từ chất liệu cotton. Quần có thiết kế trơn và đi kèm kiểu túi xéo, tạo nên sự thoải mái và phong cách hiện đại cho người mặc.',
                'category_id' => 10,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Kaki Nam Premium Ống Ôm Trơn Form Slim Cropped - 10S24PCA001P',
                'price_import' => 638000,
                'price_sell' => 638000,
                'img' => 'quan-kaki-2-1.jpg',
                'description' => 'quần kaki dành cho nam, có form dáng slim cropped (vừa ôm vừa ngắn) và làm từ chất liệu cotton polyester. Quần có thiết kế trơn và đi kèm kiểu túi xéo, tạo nên sự thoải mái và phong cách hiện đại cho người mặc.',
                'category_id' => 10,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Cargo Nam Túi Hộp Ống Rộng Trơn Form Wide Leg - 10S24PCA003',
                'price_import' => 638000,
                'price_sell' => 638000,
                'img' => 'quan-kaki-3-1.jpg',
                'description' => 'quần kaki dành cho nam, có form dáng Wide Leg (xẻ rộng) và được làm từ chất liệu 100% cotton. Quần có thiết kế trơn và đi kèm kiểu túi lớn, mang lại sự thoải mái và phong cách năng động cho người mặc.',
                'category_id' => 10,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Kaki Nam Cotton Ống Suông Form Straight Crop - 10F23PCA007',
                'price_import' => 569000,
                'price_sell' => 569000,
                'img' => 'quan-kaki-4-1.jpg',
                'description' => 'quần kaki dành cho nam, có form dáng straight crop (vừa ôm vừa ngắn). Quần được làm từ chất liệu cotton, mang đến sự thoải mái và phong cách thời trang hiện đại cho người mặc.',
                'category_id' => 10,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Kaki Nam Ống Rộng Xếp Ly Trơn Form Wide Leg - 10F22PCA018R1',
                'price_import' => 609000,
                'price_sell' => 609000,
                'img' => 'quan-kaki-5-1.jpg',
                'description' => 'quần kaki dành cho nam, có form dáng Wide Leg (xẻ rộng) và làm từ chất liệu khaki. Quần có thiết kế trơn, mang đến sự thoải mái và phong cách đơn giản, lịch lãm cho người mặc.',
                'category_id' => 10,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Kaki Nam Ống Rộng Premium Limited Form Wide Leg - 10F23PCA005L',
                'price_import' => 1276000,
                'price_sell' => 1276000,
                'img' => 'quan-kaki-6-1.jpg',
                'description' => 'quần kaki dành cho nam, có form dáng Wide Leg (xẻ rộng) và làm từ chất liệu cotton. Quần có thiết kế trơn, mang đến sự thoải mái và phong cách thời trang cho người mặc.',
                'category_id' => 10,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Short Nam Ống Đứng Cotton Spandex Trơn Form Straight -10S24PSH003',
                'price_import' => 422000,
                'price_sell' => 422000,
                'img' => 'quan-short-1-1.jpg',
                'description' => 'quần short dành cho nam, có form dáng straight (vừa ôm vừa thẳng) và làm từ chất liệu cotton spandex. Quần có thiết kế trơn và đi kèm kiểu túi xéo, tạo nên sự thoải mái và phong cách hiện đại cho người mặc.',
                'category_id' => 11,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Short Nỉ Nam Ống Rộng 100% Cotton Trơn Form Loose - 10S24PKS001',
                'price_import' => 373000,
                'price_sell' => 373000,
                'img' => 'quan-short-2-1.jpg',
                'description' => 'quần short dành cho nam, có form dáng loose (rộng rãi) và làm từ chất liệu 100% cotton. Quần có thiết kế trơn và đi kèm kiểu túi xéo, mang đến sự thoải mái và phong cách thời trang bình dị cho người mặc.',
                'category_id' => 11,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Short Nam Lưng Thun Dây Rút Trơn Form Loose - 10S24PSH002',
                'price_import' => 441000,
                'price_sell' => 441000,
                'img' => 'quan-short-3-1.jpg',
                'description' => 'quần short dành cho nam, có form dáng loose (rộng rãi) và làm từ chất liệu 100% cotton. Quần có thiết kế trơn và đi kèm kiểu túi thẳng, tạo nên sự thoải mái và phong cách thời trang bình dị cho người mặc.',
                'category_id' => 11,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Short Nam Ống Rộng Lưng Thun Có Túi Trơn Form Loose - 10S24PKS002',
                'price_import' => 392000,
                'price_sell' => 392000,
                'img' => 'quan-short-4-1.jpg',
                'description' => 'quần short dành cho nam, có form dáng loose (rộng rãi) và làm từ chất liệu 100% cotton. Quần có thiết kế trơn và đi kèm kiểu túi mổ, tạo nên sự thoải mái và phong cách thời trang bình dị, thích hợp cho các hoạt động ngoài trời và hàng ngày.',
                'category_id' => 11,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Short Nam Ống Rộng Xẻ Tà Dây Rút Trơn Form Loose - 10S24PSH005',
                'price_import' => 324000,
                'price_sell' => 324000,
                'img' => 'quan-short-5-1.jpg',
                'description' => 'quần short dành cho nam, có form dáng loose (rộng rãi) và làm từ chất liệu polyester. Quần có thiết kế trơn và đi kèm kiểu túi thẳng, mang đến sự thoải mái và phong cách hiện đại cho người mặc. Chất liệu polyester thường có khả năng thoáng khí tốt và dễ chăm sóc, phù hợp cho các hoạt động ngoài trời và trong mùa hè.',
                'category_id' => 11,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Short Nam Premium Ống Đứng Trơn Form Straight - 10S24PSH001P',
                'price_import' => 520000,
                'price_sell' => 520000,
                'img' => 'quan-short-6-1.jpg',
                'description' => 'quần short dành cho nam, có form dáng straight (thẳng) và làm từ chất liệu cotton polyester. Quần có thiết kế trơn và đi kèm kiểu túi xéo, mang đến sự thoải mái và phong cách thời trang cho người mặc. Chất liệu cotton polyester kết hợp giữa tính thoáng mát của cotton và độ bền của polyester, phù hợp cho các hoạt động thường ngày và ngoài trời.',
                'category_id' => 11,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Thun Tay Ngắn Unisex Cotton In Hình Form Loose - 10S24TSSU006',
                'price_import' => 245000,
                'price_sell' => 245000,
                'img' => 'ao-thun-nu-1-1.jpg',
                'description' => 'Áo thun unisex được làm từ chất liệu cotton mềm mại, thoáng mát, với kiểu dáng form loose rộng rãi, thoải mái. Áo có in hình họa tiết bắt mắt, trẻ trung, phù hợp cho cả nam và nữ.',
                'category_id' => 12,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Thun Nữ Tay Ngắn Trơn 100% Cotton Form Regular - 10S24TSSW001',
                'price_import' => 245000,
                'price_sell' => 245000,
                'img' => 'ao-thun-nu-2-1.jpg',
                'description' => 'Áo thun nữ được làm từ chất liệu cotton 100% mềm mại, thoáng mát, với kiểu dáng form regular vừa vặn, tôn dáng. Áo có thiết kế trơn đơn giản, phù hợp cho mọi hoạt động.',
                'category_id' => 12,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Thun Thể Thao Nữ Tay Ngắn Co Giãn Form Slim Cropped - 10S24TSSAW004',
                'price_import' => 299000,
                'price_sell' => 299000,
                'img' => 'ao-thun-nu-3-1.jpg',
                'description' => 'Áo thun thể thao nữ được làm từ chất liệu co giãn tốt, với kiểu dáng form slim ôm sát cơ thể, tôn dáng. Áo có thiết kế ngắn croptop trẻ trung, năng động.',
                'category_id' => 12,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Polo Nữ Lửng Tay Ngắn Cotton Trơn Form Regular Cropped - 10F23POLW004',
                'price_import' => 349000,
                'price_sell' => 349000,
                'img' => 'ao-thun-nu-4-1.jpg',
                'description' => 'Áo polo nữ được làm từ chất liệu cotton mềm mại, thoáng mát, với kiểu dáng form regular vừa vặn, tôn dáng. Áo có thiết kế cổ bẻ thanh lịch, trẻ trung.',
                'category_id' => 12,
                'brand_id' => 7,
            ],
            [
                'name' => ' Áo Thun Nữ Tay Ngắn Cổ Tròn Sọc Gân Trơn Form Fitted - 10S23TSSW001',
                'price_import' => 245000,
                'price_sell' => 245000,
                'img' => 'ao-thun-nu-5-1.jpg',
                'description' => ' Áo thun nữ được làm từ chất liệu sọc gân mềm mại, thoáng mát, với kiểu dáng form fitted ôm sát cơ thể, tôn dáng. Áo có thiết kế cổ tròn đơn giản, basic.',
                'category_id' => 12,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Thun Nữ Tay Ngắn Cổ Tròn Kẻ Sọc Ngang Form Fitted - 10S23TSSW012',
                'price_import' => 245000,
                'price_sell' => 245000,
                'img' => 'ao-thun-nu-6-1.jpg',
                'description' => 'Áo thun nữ được làm từ chất liệu cotton mềm mại, thoáng mát, với kiểu dáng form fitted ôm sát cơ thể, tôn dáng. Áo có thiết kế kẻ sọc ngang trẻ trung, năng động.',
                'category_id' => 12,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sơ Mi Nữ Cổ Bẻ Chất Liệu Cotton Lụa Mềm Mại',
                'price_import' => 245000,
                'price_sell' => 349000,
                'img' => 'ao-somi-nu-1-1.jpg',
                'description' => 'Áo sơ mi nữ cổ bẻ được làm từ chất liệu cotton lụa mềm mại, thoáng mát, với kiểu dáng form regular vừa vặn, tôn dáng. Áo có thiết kế cổ bẻ thanh lịch, tay dài, phù hợp cho mọi hoạt động.',
                'category_id' => 13,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sơ Mi Nữ Cổ Bẻ Chất Liệu Cotton Poplin Mịn Màng',
                'price_import' => 245000,
                'price_sell' => 349000,
                'img' => 'ao-somi-nu-2-1.jpg',
                'description' => 'Áo sơ mi nữ cổ bẻ được làm từ chất liệu cotton poplin mịn màng, thoáng mát, với kiểu dáng form regular vừa vặn, tôn dáng. Áo có thiết kế cổ bẻ thanh lịch, tay dài, phù hợp cho mọi hoạt động.',
                'category_id' => 13,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sơ Mi Nữ Cổ Bẻ Chất Liệu Linen Thoáng Mát',
                'price_import' => 349000,
                'price_sell' => 499000,
                'img' => 'ao-somi-nu-3-1.jpg',
                'description' => 'Áo sơ mi nữ cổ bẻ được làm từ chất liệu linen thoáng mát, với kiểu dáng form regular vừa vặn, tôn dáng. Áo có thiết kế cổ bẻ thanh lịch, tay dài, phù hợp cho mọi hoạt động.',
                'category_id' => 13,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sơ Mi Nữ Cổ Bẻ Chất Liệu Cotton Lụa Mềm Mại Tay Ngắn',
                'price_import' => 220000,
                'price_sell' => 329000,
                'img' => 'ao-somi-nu-4-1.jpg',
                'description' => 'Áo sơ mi nữ cổ bẻ được làm từ chất liệu cotton lụa mềm mại, thoáng mát, với kiểu dáng form regular vừa vặn, tôn dáng. Áo có thiết kế cổ bẻ thanh lịch, tay ngắn, phù hợp cho mọi hoạt động.',
                'category_id' => 13,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sơ Mi Nữ Cổ Bẻ Chất Liệu Cotton Poplin Mịn Màng Tay Ngắn',
                'price_import' => 220000,
                'price_sell' => 329000,
                'img' => 'ao-somi-nu-5-1.jpg',
                'description' => 'Áo sơ mi nữ cổ bẻ được làm từ chất liệu cotton poplin mịn màng, thoáng mát, với kiểu dáng form regular vừa vặn, tôn dáng. Áo có thiết kế cổ bẻ thanh lịch, tay ngắn, phù hợp cho mọi hoạt động.',
                'category_id' => 13,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sơ Mi Nữ Cổ Bẻ Chất Liệu Linen Thoáng Mát Tay Ngắn',
                'price_import' => 299000,
                'price_sell' => 399000,
                'img' => 'ao-somi-nu-6-1.jpg',
                'description' => 'Áo sơ mi nữ cổ bẻ được làm từ chất liệu linen thoáng mát, với kiểu dáng form regular vừa vặn, tôn dáng. Áo có thiết kế cổ bẻ thanh lịch, tay ngắn, phù hợp cho mọi hoạt động.',
                'category_id' => 13,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Khoác Nữ Dáng Dài Chất Liệu Cotton Dày Dặn',
                'price_import' => 499000,
                'price_sell' => 799000,
                'img' => 'ao-khoac-nu-1-1.jpg',
                'description' => 'Áo khoác nữ dáng dài được làm từ chất liệu cotton dày dặn, giữ ấm tốt, với kiểu dáng form regular vừa vặn, tôn dáng. Áo có thiết kế cổ bẻ thanh lịch, tay dài, có đai eo và túi hai bên, phù hợp cho những ngày se lạnh.',
                'category_id' => 14,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Khoác Nữ Bomber Lông Cừu Dày Dặn',
                'price_import' => 599000,
                'price_sell' => 899000,
                'img' => 'ao-khoac-nu-2-1.jpg',
                'description' => 'Áo khoác nữ bomber lông cừu dày dặn, giữ ấm tốt, với kiểu dáng form regular vừa vặn, trẻ trung. Áo có thiết kế cổ bẻ, tay dài, có bo cổ tay và bo gấu, túi hai bên và khóa kéo, phù hợp cho những ngày lạnh.',
                'category_id' => 14,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Khoác Nữ Dáng Ngắn Chất Liệu Polyester Chống Nước',
                'price_import' => 399000,
                'price_sell' => 599000,
                'img' => 'ao-khoac-nu-3-1.jpg',
                'description' => 'Áo khoác nữ dáng ngắn được làm từ chất liệu polyester chống nước tốt, với kiểu dáng form regular vừa vặn, trẻ trung. Áo có thiết kế cổ bẻ, tay dài, có bo cổ tay và bo gấu, túi hai bên và khóa kéo, phù hợp cho những ngày mưa hoặc gió.',
                'category_id' => 14,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Khoác Nữ Chất Liệu Dù Dày Dặn Có Mũ',
                'price_import' => 449000,
                'price_sell' => 649000,
                'img' => 'ao-khoac-nu-4-1.jpg',
                'description' => 'Áo khoác nữ chất liệu dù dày dặn, giữ ấm tốt, có mũ, với kiểu dáng form regular vừa vặn, trẻ trung. Áo có thiết kế cổ bẻ, tay dài, có bo cổ tay và bo gấu, túi hai bên và khóa kéo, phù hợp cho những ngày lạnh hoặc gió.',
                'category_id' => 14,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Khoác Nữ Dáng Dài Chất Liệu Cotton Mỏng Nhẹ',
                'price_import' => 349000,
                'price_sell' => 549000,
                'img' => 'ao-khoac-nu-5-1.jpg',
                'description' => 'Áo khoác nữ dáng dài được làm từ chất liệu cotton mỏng nhẹ, thoáng mát, với kiểu dáng form regular vừa vặn, tôn dáng. Áo có thiết kế cổ bẻ thanh lịch, tay dài, có đai eo và túi hai bên, phù hợp cho những ngày se lạnh.',
                'category_id' => 14,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Khoác Nữ Chất Liệu Da PU Mềm Mại',
                'price_import' => 599000,
                'price_sell' => 899000,
                'img' => 'ao-khoac-nu-6-1.jpg',
                'description' => 'Áo khoác nữ chất liệu da PU mềm mại, cao cấp, với kiểu dáng form regular vừa vặn, cá tính. Áo có thiết kế cổ bẻ, tay dài, có khóa kéo và túi hai bên, phù hợp cho những ngày lạnh hoặc muốn thể hiện phong cách thời trang.',
                'category_id' => 14,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Hoodie Nữ Form Rộng Chất Liệu Nỉ Cotton Mềm Mại',
                'price_import' => 299000,
                'price_sell' => 449000,
                'img' => 'hoodie-nu-1-1.jpg',
                'description' => 'Áo hoodie nữ form rộng được làm từ chất liệu nỉ cotton mềm mại, thoáng mát, với kiểu dáng form rộng thoải mái, năng động. Áo có thiết kế mũ trùm đầu, tay dài, túi kangaroo trước bụng và có dây rút điều chỉnh độ rộng mũ và gấu áo, phù hợp cho mọi hoạt động.',
                'category_id' => 15,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sweater Nữ Cổ Lệch Vai Chất Liệu Len Mềm Mại',
                'price_import' => 349000,
                'price_sell' => 499000,
                'img' => 'hoodie-nu-2-1.jpg',
                'description' => 'Áo sweater nữ cổ lệch vai được làm từ chất liệu len mềm mại, ấm áp, với kiểu dáng cổ lệch vai độc đáo, nữ tính. Áo có thiết kế cổ tròn, tay dài, bo cổ tay và bo gấu, phù hợp cho những ngày se lạnh.',
                'category_id' => 15,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Hoodie Nữ Cổ Bẻ Chất Liệu Nỉ Cotton Mềm Mại',
                'price_import' => 299000,
                'price_sell' => 449000,
                'img' => 'hoodie-nu-3-1.jpg',
                'description' => 'Áo hoodie nữ cổ bẻ được làm từ chất liệu nỉ cotton mềm mại, thoáng mát, với kiểu dáng cổ bẻ thanh lịch, trẻ trung. Áo có thiết kế mũ trùm đầu, tay dài, túi kangaroo trước bụng và có dây rút điều chỉnh độ rộng mũ và gấu áo, phù hợp cho mọi hoạt động.',
                'category_id' => 15,
                'brand_id' => 7,
            ],
            [
                'name' => 'Áo Sweater Nữ Cổ Tròn Chất Liệu Len Mềm Mại',
                'price_import' => 329000,
                'price_sell' => 479000,
                'img' => 'hoodie-nu-4-1.jpg',
                'description' => 'Áo sweater nữ cổ tròn được làm từ chất liệu len mềm mại, ấm áp, với kiểu dáng cổ tròn basic, dễ mặc. Áo có thiết kế tay dài, bo cổ tay và bo gấu, phù hợp cho những ngày se lạnh.',
                'category_id' => 15,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Jean Nữ Ống Đứng Trơn Form Straight Cropped',
                'price_import' => 349000,
                'price_sell' => 499000,
                'img' => 'quan-jean-nu-1-1.jpg',
                'description' => 'Quần jean nữ ống đứng trơn form straight cropped được làm từ chất liệu denim co giãn nhẹ, thoải mái, với kiểu dáng ống đứng basic, trẻ trung. Quần có thiết kế cạp cao, khóa kéo và khuy cài, túi trước và túi sau, chiều dài cropped trendy, phù hợp cho mọi hoạt động.',
                'category_id' => 16,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Jean Nữ Ống Suông Trơn Form Straight Cropped',
                'price_import' => 349000,
                'price_sell' => 499000,
                'img' => 'quan-jean-nu-2-1.jpg',
                'description' => 'Quần jean nữ ống suông trơn form straight cropped được làm từ chất liệu denim co giãn nhẹ, thoải mái, với kiểu dáng ống suông trendy, thanh lịch. Quần có thiết kế cạp cao, khóa kéo và khuy cài, túi trước và túi sau, chiều dài cropped trẻ trung, phù hợp cho mọi hoạt động.',
                'category_id' => 16,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Jean Nữ Dye Ống Suông Form Straight Cropped',
                'price_import' => 449000,
                'price_sell' => 649000,
                'img' => 'quan-jean-nu-3-1.jpg',
                'description' => 'Quần jean nữ dye ống suông form straight cropped được làm từ chất liệu denim co giãn nhẹ, thoải mái, với kiểu dáng ống suông trendy, cá tính. Quần có thiết kế cạp cao, khóa kéo và khuy cài, túi trước và túi sau, chiều dài cropped trẻ trung, hiệu ứng dye độc đáo, phù hợp cho mọi hoạt động.',
                'category_id' => 16,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Jean Nữ Trơn Ống Đứng Túi Đắp Form Straight',
                'price_import' => 399000,
                'price_sell' => 599000,
                'img' => 'quan-jean-nu-4-1.jpg',
                'description' => 'Quần jean nữ trơn ống đứng túi đắp form straight được làm từ chất liệu denim co giãn nhẹ, thoải mái, với kiểu dáng ống đứng basic, trẻ trung. Quần có thiết kế cạp cao, khóa kéo và khuy cài, túi trước và túi đắp sau, form straight tôn dáng, phù hợp cho mọi hoạt động.',
                'category_id' => 16,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Jean Nữ Ống Ôm Trơn Form Slim',
                'price_import' => 329000,
                'price_sell' => 479000,
                'img' => 'quan-jean-nu-5-1.jpg',
                'description' => 'Quần jean nữ ống ôm trơn form slim được làm từ chất liệu denim co giãn nhẹ, thoải mái, với kiểu dáng ôm body tôn dáng. Quần có thiết kế cạp cao, khóa kéo và khuy cài, túi trước và túi sau, form slim ôm sát, phù hợp cho những bạn yêu thích phong cách cá tính.',
                'category_id' => 16,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Jean Nữ Ống Suông Túi Thêu Form Straight Cropped',
                'price_import' => 429000,
                'price_sell' => 629000,
                'img' => 'quan-jean-nu-6-1.jpg',
                'description' => 'Quần jean nữ ống suông túi thêu form straight cropped được làm từ chất liệu denim co giãn nhẹ, thoải mái, với kiểu dáng ống suông trendy, thanh lịch. Quần có thiết kế cạp cao, khóa kéo và khuy cài, túi trước và túi sau thêu họa tiết, chiều dài cropped trẻ trung, phù hợp cho mọi hoạt động.',
                'category_id' => 16,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Kaki Nữ Ống Suông Premium Limited Form Straight',
                'price_import' => 499000,
                'price_sell' => 749000,
                'img' => 'quan-kaki-nu-1-1.jpg',
                'description' => 'Quần kaki nữ ống suông premium limited form straight được làm từ chất liệu kaki dày dặn, cao cấp, với kiểu dáng ống suông thanh lịch, tôn dáng. Quần có thiết kế cạp cao, khóa kéo và khuy cài, túi trước và túi sau, form straight vừa vặn, phù hợp cho mọi hoạt động.',
                'category_id' => 17,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Kaki Nữ Ống Đứng Ủi Ly Trơn Form Straight',
                'price_import' => 399000,
                'price_sell' => 599000,
                'img' => 'quan-kaki-nu-2-1.jpg',
                'description' => 'Quần kaki nữ ống đứng ủi ly trơn form straight được làm từ chất liệu kaki mềm mại, thoáng mát, với kiểu dáng ống đứng basic, trẻ trung. Quần có thiết kế cạp cao, khóa kéo và khuy cài, túi trước và túi sau, ủi ly tạo điểm nhấn, form straight tôn dáng, phù hợp cho mọi hoạt động.',
                'category_id' => 17,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Kaki Nữ Ống Rộng Rayon Xếp Ly Trơn Form Wide Leg',
                'price_import' => 449000,
                'price_sell' => 649000,
                'img' => 'quan-kaki-nu-3-1.jpg',
                'description' => 'Quần kaki nữ ống rộng rayon xếp ly trơn form wide leg được làm từ chất liệu rayon mềm mại, mát mẻ, với kiểu dáng ống rộng trendy, thoải mái. Quần có thiết kế cạp cao, khóa kéo và khuy cài, xếp ly tạo sự bồng bềnh, form wide leg che khuyết điểm, phù hợp cho mọi hoạt động.',
                'category_id' => 17,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Kaki Nữ Trơn Xếp Ly Đôi Form Wide Leg',
                'price_import' => 399000,
                'price_sell' => 599000,
                'img' => 'quan-kaki-nu-4-1.jpg',
                'description' => 'Quần kaki nữ trơn xếp ly đôi form wide leg được làm từ chất liệu kaki mềm mại, thoáng mát, với kiểu dáng ống rộng trendy, thoải mái. Quần có thiết kế cạp cao, khóa kéo và khuy cài, xếp ly đôi tạo điểm nhấn, form wide leg che khuyết điểm, phù hợp cho mọi hoạt động.',
                'category_id' => 17,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Kaki Nữ Ủi Ly Trơn Form Carrot Crop',
                'price_import' => 349000,
                'price_sell' => 499000,
                'img' => 'quan-kaki-nu-5-1.jpg',
                'description' => 'Quần kaki nữ ủi ly trơn form carrot crop được làm từ chất liệu kaki mềm mại, thoáng mát, với kiểu dáng carrot crop trẻ trung, năng động. Quần có thiết kế cạp cao, khóa kéo và khuy cài, ủi ly tạo điểm nhấn, form carrot ôm đùi, phù hợp cho mọi hoạt động.',
                'category_id' => 17,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Kaki Nữ Lửng Túi Ẩn Form Straight Crop',
                'price_import' => 329000,
                'price_sell' => 479000,
                'img' => 'quan-kaki-nu-6-1.jpg',
                'description' => 'Quần kaki nữ lửng túi ẩn form straight crop được làm từ chất liệu kaki mềm mại, thoáng mát, với kiểu dáng lửng trendy, trẻ trung. Quần có thiết kế cạp cao, khóa kéo và khuy cài, túi ẩn trước, form straight vừa vặn, phù hợp cho mọi hoạt động.',
                'category_id' => 17,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Short Nữ Ống Rộng Lưng Thun Trơn Form Loose',
                'price_import' => 299000,
                'price_sell' => 449000,
                'img' => 'quan-short-nu-1-1.jpg',
                'description' => 'Quần short nữ ống rộng lưng thun trơn form loose được làm từ chất liệu mềm mại, thoáng mát, với kiểu dáng ống rộng trendy, thoải mái. Quần có thiết kế cạp chun co giãn, túi trước và túi sau, form loose rộng rãi, phù hợp cho mọi hoạt động.',
                'category_id' => 18,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Short Nữ Cotton Polyester Xếp Ly Trơn Form Slim',
                'price_import' => 349000,
                'price_sell' => 499000,
                'img' => 'quan-short-nu-2-1.jpg',
                'description' => 'Quần short nữ cotton polyester xếp ly trơn form slim được làm từ chất liệu cotton polyester mềm mại, thoáng mát, với kiểu dáng ôm body tôn dáng. Quần có thiết kế cạp cao, khóa kéo và khuy cài, xếp ly tạo điểm nhấn, form slim ôm sát, phù hợp cho những bạn yêu thích phong cách cá tính.',
                'category_id' => 18,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Short Nữ Ống Rộng Kẻ Sọc Cotton Dây Rút Form Loose',
                'price_import' => 329000,
                'price_sell' => 479000,
                'img' => 'quan-short-nu-3-1.jpg',
                'description' => 'Quần short nữ ống rộng kẻ sọc cotton dây rút form loose được làm từ chất liệu cotton mềm mại, thoáng mát, với kiểu dáng ống rộng trendy, thoải mái. Quần có thiết kế cạp thun co giãn, dây rút điều chỉnh độ rộng eo, kẻ sọc thời trang, form loose rộng rãi, phù hợp cho mọi hoạt động.',
                'category_id' => 18,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Short Nữ Linen Ống Rộng Túi Thẳng Trơn Form Loose',
                'price_import' => 399000,
                'price_sell' => 599000,
                'img' => 'quan-short-nu-4-1.jpg',
                'description' => 'Quần short nữ linen ống rộng túi thẳng trơn form loose được làm từ chất liệu linen cao cấp, mềm mại, thoáng mát, với kiểu dáng ống rộng trendy, thanh lịch. Quần có thiết kế cạp cao, khóa kéo và khuy cài, túi thẳng trước, form loose rộng rãi, phù hợp cho mọi hoạt động.',
                'category_id' => 11,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Short Thể Thao Nữ Ống Rộng Trơn Form Loose',
                'price_import' => 249000,
                'price_sell' => 399000,
                'img' => 'quan-short-nu-5-1.jpg',
                'description' => 'Quần short thể thao nữ ống rộng trơn form loose được làm từ chất liệu thun co giãn 4 chiều, mềm mại, thoáng mát, với kiểu dáng ống rộng thoải mái, năng động. Quần có thiết kế cạp chun co giãn, túi trước và túi sau, form loose rộng rãi, phù hợp cho các hoạt động thể thao.',
                'category_id' => 18,
                'brand_id' => 7,
            ],
            [
                'name' => 'Quần Short Jean Nữ Ống Suông Trơn Form Straight',
                'price_import' => 349000,
                'price_sell' => 499000,
                'img' => 'quan-short-nu-6-1.jpg',
                'description' => 'Quần short jean nữ ống suông trơn form straight được làm từ chất liệu denim co giãn nhẹ, thoải mái, với kiểu dáng ống suông trendy, thanh lịch. Quần có thiết kế cạp cao, khóa kéo và khuy cài, túi trước và túi sau, form straight vừa vặn, phù hợp cho mọi hoạt động.',
                'category_id' => 18,
                'brand_id' => 7,
            ],
            [
                'name' => 'Đầm Dài Sơ Mi Nữ Tay Ngắn Kẻ Sọc Polyester Form Loose',
                'price_import' => 499000,
                'price_sell' => 749000,
                'img' => 'dam-nu-1-1.jpg',
                'description' => 'Đầm dài sơ mi nữ tay ngắn kẻ sọc polyester form loose được làm từ chất liệu polyester mềm mại, thoáng mát, với kiểu dáng dài thanh lịch, thoải mái. Đầm có thiết kế cổ sơ mi, tay ngắn, họa tiết kẻ sọc thời trang, form loose rộng rãi, che khuyết điểm cơ thể, phù hợp cho mọi hoạt động.',
                'category_id' => 19,
                'brand_id' => 7,
            ],
            [
                'name' => 'Đầm Nữ Chữ A Sát Nách Thun 100% Cotton Trơn Form A Line',
                'price_import' => 349000,
                'price_sell' => 499000,
                'img' => 'dam-nu-2-1.jpg',
                'description' => 'Đầm nữ chữ A sát nách thun 100% cotton trơn form A line được làm từ chất liệu cotton 100% mềm mại, thoáng mát, với kiểu dáng chữ A trẻ trung, năng động. Đầm có thiết kế sát nách, form A line xòe nhẹ, che khuyết điểm cơ thể, phù hợp cho mọi hoạt động.',
                'category_id' => 19,
                'brand_id' => 7,
            ],
            [
                'name' => 'Đầm Nữ Tay Ngắn Cotton Cổ Tròn Trơn Form Regular',
                'price_import' => 299000,
                'price_sell' => 449000,
                'img' => 'dam-nu-3-1.jpg',
                'description' => 'Đầm nữ tay ngắn cotton cổ tròn trơn form regular được làm từ chất liệu cotton mềm mại, thoáng mát, với kiểu dáng basic, đơn giản. Đầm có thiết kế tay ngắn, cổ tròn, form regular vừa vặn, che khuyết điểm cơ thể, phù hợp cho mọi hoạt động.',
                'category_id' => 19,
                'brand_id' => 7,
            ],
            [
                'name' => 'Đầm Nữ 2 Dây Satin Suông Trơn Phối Voan Form Straight',
                'price_import' => 599000,
                'price_sell' => 899000,
                'img' => 'dam-nu-4-1.jpg',
                'description' => 'Đầm nữ 2 dây satin suông trơn phối voan form straight được làm từ chất liệu satin cao cấp, mềm mại, bóng mượt, với kiểu dáng suông thanh lịch, sang trọng. Đầm có thiết kế 2 dây, phối voan tạo điểm nhấn, form straight vừa vặn, che khuyết điểm cơ thể, phù hợp cho mọi hoạt động.',
                'category_id' => 19,
                'brand_id' => 7,
            ],
            [
                'name' => 'Đầm Sát Nách Suông Cổ Thuyền Ngang Trơn Form Straight',
                'price_import' => 399000,
                'price_sell' => 599000,
                'img' => 'dam-nu-5-1.jpg',
                'description' => 'Đầm sát nách suông cổ thuyền ngang trơn form straight được làm từ chất liệu mềm mại, thoáng mát, với kiểu dáng suông thanh lịch, trẻ trung. Đầm có thiết kế sát nách, cổ thuyền ngang, form straight vừa vặn, che khuyết điểm cơ thể, phù hợp cho mọi hoạt động.',
                'category_id' => 19,
                'brand_id' => 7,
            ],
            [
                'name' => 'Đầm Polo Nữ Tay Ngắn Cổ Gài Nút Trơn Form Regular',
                'price_import' => 349000,
                'price_sell' => 499000,
                'img' => 'dam-nu-6-1.jpg',
                'description' => 'Đầm polo nữ tay ngắn cổ gài nút trơn form regular được làm từ chất liệu cotton pique mềm mại, thoáng mát, với kiểu dáng polo basic, trẻ trung. Đầm có thiết kế tay ngắn, cổ gài nút, form regular vừa vặn, che khuyết điểm cơ thể, phù hợp cho mọi hoạt động.',
                'category_id' => 19,
                'brand_id' => 7,
            ],
            [
                'name' => 'Chân Váy Nữ Dài Kẻ Sọc Cotton Nhún Lưng Form Loose',
                'price_import' => 499000,
                'price_sell' => 749000,
                'img' => 'chan-vay-nu-1-1.jpg',
                'description' => 'Chân váy nữ dài kẻ sọc cotton nhún lưng form loose được làm từ chất liệu cotton mềm mại, thoáng mát, với kiểu dáng dài thanh lịch, thoải mái. Chân váy có thiết kế họa tiết kẻ sọc thời trang, nhún lưng tạo điểm nhấn, form loose rộng rãi, che khuyết điểm cơ thể, phù hợp cho mọi hoạt động.',
                'category_id' => 20,
                'brand_id' => 7,
            ],
            [
                'name' => 'Chân Váy Nữ Dài 100% Cotton Kẻ Sọc Form Loose',
                'price_import' => 399000,
                'price_sell' => 599000,
                'img' => 'chan-vay-nu-2-1.jpg',
                'description' => 'Chân váy nữ dài 100% cotton kẻ sọc form loose được làm từ chất liệu cotton 100% mềm mại, thoáng mát, với kiểu dáng dài thanh lịch, thoải mái. Chân váy có thiết kế họa tiết kẻ sọc thời trang, form loose rộng rãi, che khuyết điểm cơ thể, phù hợp cho mọi hoạt động.',
                'category_id' => 20,
                'brand_id' => 7,
            ],
            [
                'name' => 'Chân Váy Chữ A Nữ Mini Vải Tweed Trơn Form A Line',
                'price_import' => 349000,
                'price_sell' => 499000,
                'img' => 'chan-vay-nu-3-1.jpg',
                'description' => 'Chân váy chữ A nữ mini vải tweed trơn form A line được làm từ chất liệu vải tweed cao cấp, dày dặn, với kiểu dáng chữ A trẻ trung, năng động. Chân váy có thiết kế cạp cao, khóa kéo sau, form A line xòe nhẹ, che khuyết điểm cơ thể, phù hợp cho mọi hoạt động.',
                'category_id' => 20,
                'brand_id' => 7,
            ],
            [
                'name' => 'Chân Váy Maxi Dài Rayon Nhún Eo Xếp Ly Trơn Form A-Line Midi',
                'price_import' => 599000,
                'price_sell' => 899000,
                'img' => 'chan-vay-nu-4-1.jpg',
                'description' => 'Chân váy maxi dài rayon nhún eo xếp ly trơn form A-line midi được làm từ chất liệu rayon mềm mại, mát mẻ, với kiểu dáng maxi dài thanh lịch, nữ tính. Chân váy có thiết kế kế họa tiết kẻ sọc thời trang, form loose rộng rãi, che khuyết điểm cơ thể, phù hợp cho mọi hoạt động.',
                'category_id' => 20,
                'brand_id' => 7,
            ],
            [
                'name' => 'Chân Váy Chữ A Jean Nữ Họa Tiết In Laser Form A Line',
                'price_import' => 449000,
                'price_sell' => 679000,
                'img' => 'chan-vay-nu-5-1.jpg',
                'description' => 'Chân váy chữ A jean nữ họa tiết in laser form A line được làm từ chất liệu jean cao cấp, co giãn nhẹ, thoải mái, với kiểu dáng chữ A trẻ trung, năng động. Chân váy có thiết kế họa tiết in laser thời trang, form A line xòe nhẹ, che khuyết điểm cơ thể, phù hợp cho mọi hoạt động.',
                'category_id' => 20,
                'brand_id' => 7,
            ],
            [
                'name' => 'Chân Váy Midi Nữ Lưng Thun Xếp Ly Trơn Form Aline',
                'price_import' => 329000,
                'price_sell' => 479000,
                'img' => 'chan-vay-nu-6-1.jpg',
                'description' => 'Chân váy midi nữ lưng thun xếp ly trơn form Aline được làm từ chất liệu mềm mại, thoáng mát, với kiểu dáng midi thanh lịch, nữ tính. Chân váy có thiết kế lưng thun co giãn, xếp ly tạo điểm nhấn, form Aline ôm nhẹ, che khuyết điểm cơ thể, phù hợp cho mọi hoạt động.',
                'category_id' => 20,
                'brand_id' => 7,
            ],
            [
                'name' => 'Nón Lưỡi Trai Nam Freesize',
                'price_import' => 39000,
                'price_sell' => 59000,
                'img' => 'non-luoi-trai-nam-1-1.jpg',
                'description' => 'Nón lưỡi trai nam freesize được làm từ chất liệu cotton mềm mại, thoáng mát, với kiểu dáng basic, trẻ trung. Nón có thiết kế lưỡi trai cong, ôm sát đầu, có thể điều chỉnh độ rộng bằng khóa dán, phù hợp cho mọi hoạt động.',
                'category_id' => 21,
                'brand_id' => 7,
            ],
            [
                'name' => 'Mũ Lưỡi Trai Nam Coffee Kẻ Sọc Thêu Chữ Freesize',
                'price_import' => 49000,
                'price_sell' => 74000,
                'img' => 'non-luoi-trai-nam-2-1.jpg',
                'description' => 'Mũ lưỡi trai nam coffee kẻ sọc thêu chữ freesize được làm từ chất liệu cotton mềm mại, thoáng mát, với kiểu dáng basic, thời trang. Mũ có thiết kế lưỡi trai cong, ôm sát đầu, có thể điều chỉnh độ rộng bằng khóa dán, họa tiết kẻ sọc, thêu chữ nổi bật, phù hợp cho mọi hoạt động.',
                'category_id' => 21,
                'brand_id' => 7,
            ],
            [
                'name' => 'Nón Lưỡi Trai Nam 100% Cotton Thêu Chữ Nổi Freesize',
                'price_import' => 59000,
                'price_sell' => 89000,
                'img' => 'non-luoi-trai-nam-3-1.jpg',
                'description' => 'Nón lưỡi trai nam 100% cotton thêu chữ nổi freesize được làm từ chất liệu cotton 100% mềm mại, thoáng mát, với kiểu dáng basic, sang trọng. Mũ có thiết kế lưỡi trai cong, ôm sát đầu, có thể điều chỉnh độ rộng bằng khóa dán, thêu chữ nổi bật, phù hợp cho mọi hoạt động.',
                'category_id' => 21,
                'brand_id' => 7,
            ],
            [
                'name' => 'Băng Đô Vải Kẻ Sọc Caro',
                'price_import' => 29000,
                'price_sell' => 44000,
                'img' => 'bang-do-vai-1-1.jpg',
                'description' => 'Băng đô vải kẻ sọc caro được làm từ chất liệu vải mềm mại, co giãn tốt, với kiểu dáng basic, thời trang. Băng đô có thiết kế bản rộng, họa tiết kẻ sọc caro, giúp giữ tóc gọn gàng, tạo điểm nhấn cho phong cách.',
                'category_id' => 21,
                'brand_id' => 7,
            ],
            [
                'name' => 'Nón Bucket Unisex Hoa Văn Phối Dây Freesize',
                'price_import' => 49000,
                'price_sell' => 74000,
                'img' => 'non-bucket-unisex-1-1.jpg',
                'description' => 'Nón bucket unisex hoa văn phối dây freesize được làm từ chất liệu cotton mềm mại, thoáng mát, với kiểu dáng basic, thời trang. Nón có thiết kế vành tròn, họa tiết hoa văn, phối dây ruy băng, tạo điểm nhấn cho phong cách, phù hợp cho cả nam và nữ.',
                'category_id' => 21,
                'brand_id' => 7,
            ],
            [
                'name' => 'Nón Lưỡi Trai Nữ Cotton Thắt Nơ Kẻ Sọc',
                'price_import' => 39000,
                'price_sell' => 59000,
                'img' => 'non-luoi-trai-nu-1-1.jpg',
                'description' => 'Nón lưỡi trai nữ cotton thắt nơ kẻ sọc được làm từ chất liệu cotton mềm mại, thoáng mát, với kiểu dáng basic, nữ tính. Nón có thiết kế lưỡi trai cong, ôm sát đầu, có thể điều chỉnh độ rộng bằng khóa dán, họa tiết kẻ sọc, thắt nơ phía trước, tạo điểm nhấn cho phong cách.',
                'category_id' => 21,
                'brand_id' => 7,
            ],
            [
                'name' => 'Túi Tote Unisex Trơn Phối Nhãn Freesize',
                'price_import' => 399000,
                'price_sell' => 599000,
                'img' => 'tui-tote-unisex-1-1.jpg',
                'description' => 'Túi tote unisex trơn phối nhãn freesize được làm từ chất liệu canvas dày dặn, bền bỉ, với kiểu dáng basic, trẻ trung. Túi có thiết kế chữ nhật rộng rãi, phối nhãn da, có thể đựng nhiều vật dụng, phù hợp cho cả nam và nữ.',
                'category_id' => 22,
                'brand_id' => 7,
            ],
            [
                'name' => 'Túi Đeo Bán Nguyệt Dành Cho Nữ Trơn Freesize',
                'price_import' => 299000,
                'price_sell' => 449000,
                'img' => 'tui-deo-ban-nguyet-nu-1-1.jpg',
                'description' => 'Túi đeo bán nguyệt dành cho nữ trơn freesize được làm từ chất liệu da PU mềm mại, bóng mượt, với kiểu dáng bán nguyệt thời trang. Túi có thiết kế quai xách dạng xích, khoá cài kim loại, ngăn chính rộng rãi, phù hợp cho nữ giới đi chơi, dạo phố.',
                'category_id' => 22,
                'brand_id' => 7,
            ],
            [
                'name' => 'Túi Tote Unisex Kẻ Sọc Phối Màu Freesize',
                'price_import' => 449000,
                'price_sell' => 679000,
                'img' => 'tui-tote-unisex-ke-soc-1-1.jpg',
                'description' => 'Túi tote unisex kẻ sọc phối màu freesize được làm từ chất liệu canvas dày dặn, bền bỉ, với kiểu dáng basic, thời trang. Túi có thiết kế chữ nhật rộng rãi, họa tiết kẻ sọc phối màu, có thể đựng nhiều vật dụng, phù hợp cho cả nam và nữ.',
                'category_id' => 22,
                'brand_id' => 7,
            ],
            [
                'name' => 'Túi Đeo Chéo Phối Màu Chống Thấm Thiết Kế Basic',
                'price_import' => 249000,
                'price_sell' => 374000,
                'img' => 'tui-deo-cheo-2-1.jpg',
                'description' => 'Túi đeo chéo phối màu chống thấm thiết kế basic - 10S23BAG020 được làm từ chất liệu vải dù cao cấp, chống thấm nước tốt, với kiểu dáng basic, trẻ trung. Túi có thiết kế nhỏ gọn, tiện lợi, phối màu thời trang, ngăn chính rộng rãi, có thể đựng nhiều vật dụng cá nhân, phù hợp cho đi chơi, dạo phố.',
                'category_id' => 22,
                'brand_id' => 7,
            ],
            [
                'name' => 'Balo Canvas Túi Hộp Nhãn Trang Trí',
                'price_import' => 399000,
                'price_sell' => 599000,
                'img' => 'balo-canvas-tui-hop-1-1.jpg',
                'description' => 'Balo canvas túi hộp nhãn trang trí được làm từ chất liệu canvas dày dặn, bền bỉ, với kiểu dáng túi hộp thời trang. Balo có thiết kế ngăn chính rộng rãi, nhiều ngăn phụ tiện lợi, nhãn da trang trí, quai đeo vai có thể điều chỉnh, phù hợp cho đi học, đi chơi.',
                'category_id' => 22,
                'brand_id' => 7,
            ],
            [
                'name' => 'Túi Đeo Chéo Unisex Thêu Nhãn Trang Trí',
                'price_import' => 299000,
                'price_sell' => 449000,
                'img' => 'tui-deo-cheo-unisex-theu-nhan-1-1.jpg',
                'description' => 'Túi đeo chéo unisex thêu nhãn trang trí được làm từ chất liệu da PU mềm mại, bóng mượt, với kiểu dáng basic, thời trang. Túi có thiết kế quai đeo chéo có thể điều chỉnh, thêu nhãn trang trí, ngăn chính rộng rãi, phù hợp cho cả nam và nữ.',
                'category_id' => 22,
                'brand_id' => 7,
            ],

        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
