<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsColorTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $productColors = [
            ['color_id' => 10, 'product_id' => 1],
            ['color_id' => 5, 'product_id' => 2],
            ['color_id' => 6, 'product_id' => 3],
            ['color_id' => 11, 'product_id' => 4],
            ['color_id' => 13, 'product_id' => 5],
            ['color_id' => 32, 'product_id' => 6],
            ['color_id' => 6, 'product_id' => 7],
            ['color_id' => 5, 'product_id' => 8],
            ['color_id' => 5, 'product_id' => 9],
            ['color_id' => 5, 'product_id' => 10],
            ['color_id' => 5, 'product_id' => 11],
            ['color_id' => 53, 'product_id' => 12],
            ['color_id' => 2, 'product_id' => 13],
            ['color_id' => 3, 'product_id' => 14],
            ['color_id' => 4, 'product_id' => 15],
            ['color_id' => 2, 'product_id' => 16],
            ['color_id' => 5, 'product_id' => 17],
            ['color_id' => 24, 'product_id' => 18],
            ['color_id' => 10, 'product_id' => 19],
            ['color_id' => 5, 'product_id' => 20],
            ['color_id' => 5, 'product_id' => 21],
            ['color_id' => 5, 'product_id' => 22],
            ['color_id' => 1, 'product_id' => 23],
            ['color_id' => 12, 'product_id' => 24],
            ['color_id' => 12, 'product_id' => 25],
            ['color_id' => 12, 'product_id' => 26],
            ['color_id' => 12, 'product_id' => 27],
            ['color_id' => 3, 'product_id' => 28],
            ['color_id' => 11, 'product_id' => 29],
            ['color_id' => 5, 'product_id' => 30],
            ['color_id' => 24, 'product_id' => 31],
            ['color_id' => 5, 'product_id' => 32],
            ['color_id' => 24, 'product_id' => 33],
            ['color_id' => 24, 'product_id' => 34],
            ['color_id' => 24, 'product_id' => 35],
            ['color_id' => 24, 'product_id' => 36],
            ['color_id' => 5, 'product_id' => 37],
            ['color_id' => 10, 'product_id' => 38],
            ['color_id' => 6, 'product_id' => 39],
            ['color_id' => 11, 'product_id' => 40],
            ['color_id' => 5, 'product_id' => 41],
            ['color_id' => 11, 'product_id' => 42],
            ['color_id' => 5, 'product_id' => 43],
            ['color_id' => 3, 'product_id' => 44],
            ['color_id' => 3, 'product_id' => 45],
            ['color_id' => 2, 'product_id' => 46],
            ['color_id' => 5, 'product_id' => 47],
            ['color_id' => 5, 'product_id' => 48],
            ['color_id' => 5, 'product_id' => 49],
            ['color_id' => 6, 'product_id' => 50],
            ['color_id' => 5, 'product_id' => 51],
            ['color_id' => 5, 'product_id' => 52],
            ['color_id' => 4, 'product_id' => 53],
            ['color_id' => 3, 'product_id' => 54],
            ['color_id' => 14, 'product_id' => 55],
            ['color_id' => 2, 'product_id' => 56],
            ['color_id' => 24, 'product_id' => 57],
            ['color_id' => 5, 'product_id' => 58],
            ['color_id' => 3, 'product_id' => 59],
            ['color_id' => 5, 'product_id' => 60],
            ['color_id' => 5, 'product_id' => 61],
            ['color_id' => 5, 'product_id' => 62],
            ['color_id' => 5, 'product_id' => 63],
            ['color_id' => 5, 'product_id' => 64],
            ['color_id' => 5, 'product_id' => 65],
            ['color_id' => 12, 'product_id' => 66],
            ['color_id' => 5, 'product_id' => 67],
            ['color_id' => 12, 'product_id' => 68],
            ['color_id' => 12, 'product_id' => 69],
            ['color_id' => 9, 'product_id' => 70],
            ['color_id' => 11, 'product_id' => 71],
            ['color_id' => 24, 'product_id' => 72],
            ['color_id' => 23, 'product_id' => 73],
            ['color_id' => 10, 'product_id' => 74],
            ['color_id' => 24, 'product_id' => 75],
            ['color_id' => 24, 'product_id' => 76],
            ['color_id' => 6, 'product_id' => 77],
            ['color_id' => 3, 'product_id' => 78],
            ['color_id' => 10, 'product_id' => 79],
            ['color_id' => 11, 'product_id' => 80],
            ['color_id' => 5, 'product_id' => 81],
            ['color_id' => 12, 'product_id' => 82],
            ['color_id' => 14, 'product_id' => 83],
            ['color_id' => 10, 'product_id' => 84],
            ['color_id' => 9, 'product_id' => 85],
            ['color_id' => 21, 'product_id' => 86],
            ['color_id' => 11, 'product_id' => 87],
            ['color_id' => 9, 'product_id' => 88],
            ['color_id' => 2, 'product_id' => 89],
            ['color_id' => 5, 'product_id' => 90],
            ['color_id' => 41, 'product_id' => 91],
            ['color_id' => 1, 'product_id' => 92],
            ['color_id' => 5, 'product_id' => 93],
            ['color_id' => 5, 'product_id' => 94],
            ['color_id' => 2, 'product_id' => 95],
            ['color_id' => 2, 'product_id' => 96],
            ['color_id' => 6, 'product_id' => 97],
            ['color_id' => 3, 'product_id' => 98],
            ['color_id' => 24, 'product_id' => 99],
            ['color_id' => 6, 'product_id' => 100],
            ['color_id' => 5, 'product_id' => 101],
            ['color_id' => 2, 'product_id' => 102],
            ['color_id' => 3, 'product_id' => 103],
            ['color_id' => 14, 'product_id' => 104],
            ['color_id' => 9, 'product_id' => 105],
            ['color_id' => 2, 'product_id' => 106],
            ['color_id' => 5, 'product_id' => 107],
            ['color_id' => 2, 'product_id' => 108],
            ['color_id' => 3, 'product_id' => 109],
            ['color_id' => 14, 'product_id' => 110],
            ['color_id' => 9, 'product_id' => 111],
            ['color_id' => 2, 'product_id' => 112],
        ];

        DB::table('products_color')->insert($productColors);
    }
}
